### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by monkeyjp** [Rzmsdo/InstaBootstramp#1]
Hola, esta bastante bien. sin embargo hay unos puntos a mejorar antes de poder aprobarlo. 
si te fijas cuando estamos en la vista de cuadricula y hacemos scroll hacia abajo vemos que hay un espacio muy grande en blanco. 
esto se debe a que el contenido o elemento que tiene el id profile-tab-pane lo colocaste fuera del contenedor de las tabs `<div class="tab-content" id="myTabContent">`
Al igual que tienes que tener cuidado en donde abres y donde cierras las etiquetas. por ejemplo busca en donde abres la etiqueta `<ul>` y donde la estas cerrando. 
para la primera parte lo puedes solucionar dejando a tu codigo con la siguiente estructura. 

![Screenshot 2024-11-04 at 17 49 11](https://github.com/user-attachments/assets/39a2789d-4979-4203-b6ee-f3f1ce003300)

adicionalmente cuando estamos en una pantalla pequeña la vista de una sola columna se te esta descuadrando. esto es por ese col-4 que le diste a los contenedores 
![Screenshot 2024-11-04 at 17 56 38](https://github.com/user-attachments/assets/7309074b-7ae0-4301-8262-c1fe7cd38254)

**Comment by Rzmsdo** [comment]
Perfecto, trabajo en ello y lo reenvio.
Gracias
